### ISSUE TITLE
ローカル環境設定 REST API

### ISSUE THREAD

**Issue by namkim** [pres-inc/pres-paper#14]
https://www.django-rest-framework.org/

**Comment by t-itakura** [comment]
開発環境をdocker-composeで作りました。ご確認よろしくお願いします
このリポジトリの編集権限がないので、個人用のリポジトリにおきました。
https://github.com/t-itakura/django-dev-pres

**Comment by t-itakura** [comment]
djangoとmysqlの接続はできるので、ログインの認証箇所の検証などはできると思います
mysqlは5.7を使用してますが、djangoなどのライブラリのバージョンは適当なので
キムさんが使いやすいバージョンを教えていただければ修正します

**Comment by namkim** [comment]
ありがとうござます！
ローカルで確認してみます。
