### ISSUE TITLE
【 テーブル設計】研究 study

### ISSUE THREAD

**Issue by namkim** [pres-inc/pres-paper#3]
### テーブル名：study
| カラム名  | 日本語名  | 説明 |
|---|---|---|
| id  | 研究ID  |    | 
| study_title  | 研究タイトル  |   |  
| study_responsibility  | 研究責任者  |   |  
| study_manager  | 研究担当者  |   |  
| study_status  | 研究ステータス  |   |  
| delete_flg  | 削除フラグ | 0:削除前 ,1:削除済 |
| created_at  | 作成時間  |   |  
| updated_at  | 修正時間  |   |  
| deleted_at  | 修正時間  |   |

**Comment by namkim** [comment]
deleted_atがあることは、削除フラグのカラムを追加した方がいいですかね

**Comment by t-itakura** [comment]
削除された研究の再利用もありそうですし、念の為削除フラグを入れた方がいれておきますか

**Comment by t-itakura** [comment]
| カラム名 | 日本語名 | 説明 |
| ------------- | ------------- | ------------- |
| delete_flg  | 削除フラグ | 0:削除前 ,1:削除済 |
