### ISSUE TITLE
例外ハンドリングの実装

### ISSUE THREAD

**Issue by t-itakura** [pres-inc/pres-paper#79]
https://onedrive.live.com/view.aspx?cid=a7bd7ed9db79ea92&page=view&resid=A7BD7ED9DB79EA92!531&parId=A7BD7ED9DB79EA92!529&authkey=!ANjMg69uwL3xXNw&app=Excel

上記シートに沿った、エラーのハンドリングを実装する

response
```
{
  "code": 104,
  "msg":  ""
}
```

**Comment by namkim** [comment]
こちら、ちょっと調べてますが、こちらで設定できる気もしますね。
https://www.django-rest-framework.org/api-guide/exceptions/#exception-handling-in-rest-framework-views

**Comment by t-itakura** [comment]
No|コードNo|エラーメッセージ|説明
----|----|----|---- 
1|0|※空|※画面によって文言変化
2|101|ログインに失敗しました。|メールアドレスやパスワード入力間違いでのログイン不可
3|102|使用中のメールアドレスです。他のメールアドレスをしてしてください。|使用中のメールアドレスです。
4|103|再度ログインしてください。|セッション切れ
5|104|登録されてないユーザーです。|ユーザーIDが存在しない
6|105|管理者に問い合わせしてください。（105）|更新する項目が存在しない
7|106|招待URLの有効期限が切れました。|招待URLの有効期限切れ
8|107|実績がありません。|実績の各項目の数がすべて０の場合
9|108|管理者ではありません。|管理者権限がない場合
10|109|該当する研究が存在しません。|研究データの削除フラグが１、または存在しない場合
11|110|フォルダが存在しません。|フォルダの削除フラグが１、または存在しない場合
12|111|同じ名前のフォルダが存在しております。|所属されてある研究室の中で同じ名前のフォルダ名が存在する場合
14|112|ノートが存在しません。|実験データの削除フラグが１、または存在しない場合
15|113|タスクが存在しません。|タスクデータの削除フラグが１、または存在しない場合
16|114|同じ名前の研究が存在しております。|所属されてある研究室の中で同じ名前の研究が存在する場合
17|115|選択した実験担当者が存在しておりません。|選択した実験担当者が存在しない、または削除状況の場合

**Comment by t-itakura** [comment]
ステータスコードについて

| code | message |
----|---- 
| 200 | OK |
| 400 | bad request |
| 401 | unauthorized |
| 403 | forbidden |
| 404 | not found |
| 405 | method not allowed |
| 408 | timeout |
| 500 | internal server error |
| 503 | service unavaliable |
