### ISSUE TITLE
【 テーブル設計】メンバー members

### ISSUE THREAD

**Issue by namkim** [pres-inc/pres-paper#8]
### テーブル名：members
| カラム名  | 日本語名  | 説明 |
|---|---|---|
| id  | メンバーID  |    | 
| [study_id](https://github.com/pres-inc/pres-paper/issues/3)  | 研究ID  |    | 
| [experiment_id](https://github.com/pres-inc/pres-paper/issues/4)  | 実験ID  |    | 
| [user](https://github.com/pres-inc/pres-paper/issues/2)  | ユーザー   |　|

**Comment by namkim** [comment]
こちら質問ですが、メンバーを紐づく基準(必須)とするのは、実験IDと研究IDで、認識合ってますかね。

**Comment by t-itakura** [comment]
membersテーブルはサービスの利用者を管理するテーブルだと思うので
ここにはメンバーのメタ情報、ロールなどを
研究、実験テーブルにメンバーのIDを入れておけば大丈夫かと思います。
